import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/page-header";

export const Route = createFileRoute("/alerts")({
  head: () => ({ meta: [{ title: "Email Alert Rules — SNTTW Connect" }] }),
  component: AlertRules,
});

const TEMPLATE = `Subject:
Critical Spec Violation: {{process_name}} / {{parameter_name}} / Lot {{lot_id}}

Body:
A specification limit violation was detected.

Lot: {{lot_id}}
Process: {{process_name}}
Parameter: {{parameter_name}}
Measured value: {{value}}
LSL: {{lsl}}
USL: {{usl}}
Violation: {{above_usl_or_below_lsl}}
Tool: {{tool_id}}
Chamber: {{chamber_id}}
Recipe: {{recipe_id}}
Time: {{timestamp}}

Please review the lot history and take action:
{{lot_history_link}}

This message was generated by SNTTW Connect in read-only MES mode.`;

function AlertRules() {
  const [cooldown, setCooldown] = useState(30);
  const [escalateAfter, setEscalateAfter] = useState(120);
  const [emailUSL, setEmailUSL] = useState(true);
  const [emailLSL, setEmailLSL] = useState(true);
  const [emailUCL, setEmailUCL] = useState(false);
  const [emailLCL, setEmailLCL] = useState(false);
  const [dedup, setDedup] = useState(true);

  return (
    <div className="space-y-6">
      <PageHeader title="Email Alert Rules" subtitle="USL/LSL violations trigger owner emails. UCL/LCL are SPC warnings — opt-in only." />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Triggers</CardTitle></CardHeader>
          <CardContent className="space-y-3 text-sm">
            <ToggleRow label="Email on Above USL (spec)" desc="Sent to process owner." value={emailUSL} onChange={setEmailUSL} recommended />
            <ToggleRow label="Email on Below LSL (spec)" desc="Sent to process owner." value={emailLSL} onChange={setEmailLSL} recommended />
            <ToggleRow label="Email on Above UCL (control)" desc="Off by default — control warning only." value={emailUCL} onChange={setEmailUCL} />
            <ToggleRow label="Email on Below LCL (control)" desc="Off by default — control warning only." value={emailLCL} onChange={setEmailLCL} />
            <ToggleRow label="Deduplicate per lot+process+parameter" desc="Avoid duplicate alerts for the same violation." value={dedup} onChange={setDedup} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm font-semibold">Cooldown & Escalation</CardTitle></CardHeader>
          <CardContent className="space-y-4 text-sm">
            <Field label="Cooldown between identical alerts (minutes)">
              <Input type="number" value={cooldown} min={0} onChange={(e) => setCooldown(Number(e.target.value))} />
            </Field>
            <Field label="Escalate to backup owner if not acknowledged within (minutes)">
              <Input type="number" value={escalateAfter} min={0} onChange={(e) => setEscalateAfter(Number(e.target.value))} />
            </Field>
            <div className="text-xs text-muted-foreground">
              Backend hook: <code className="font-mono">sendOwnerSpecViolationEmail(violation)</code>,
              with escalation handled by <code className="font-mono">escalateUnacknowledged(violation)</code>.
            </div>
            <Button>Save rules</Button>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold">Email Template Preview</CardTitle>
          <p className="text-xs text-muted-foreground">Placeholders rendered server-side at email time.</p>
        </CardHeader>
        <CardContent>
          <pre className="overflow-auto rounded-md bg-muted/40 p-4 text-xs font-mono leading-relaxed text-foreground whitespace-pre-wrap">{TEMPLATE}</pre>
        </CardContent>
      </Card>
    </div>
  );
}

function ToggleRow({ label, desc, value, onChange, recommended }: { label: string; desc: string; value: boolean; onChange: (v: boolean) => void; recommended?: boolean }) {
  return (
    <div className="flex items-start justify-between gap-3 rounded-md border border-border p-3">
      <div>
        <div className="flex items-center gap-2 font-medium">{label}{recommended && <Badge variant="outline" className="border-success/40 bg-success/10 text-success text-[10px]">recommended</Badge>}</div>
        <div className="text-xs text-muted-foreground">{desc}</div>
      </div>
      <input type="checkbox" checked={value} onChange={(e) => onChange(e.target.checked)} className="mt-1 h-4 w-4 accent-[var(--primary)]" />
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="mb-1 block text-xs font-medium uppercase tracking-wider text-muted-foreground">{label}</label>
      {children}
    </div>
  );
}
