/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpcRouteImport } from './routes/spc'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as IndexRouteImport } from './routes/index'

const SpcRoute = SpcRouteImport.update({
  id: '/spc',
  path: '/spc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/processes': typeof ProcessesRoute
  '/spc': typeof SpcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/processes': typeof ProcessesRoute
  '/spc': typeof SpcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/processes': typeof ProcessesRoute
  '/spc': typeof SpcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/processes' | '/spc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/processes' | '/spc'
  id: '__root__' | '/' | '/processes' | '/spc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcessesRoute: typeof ProcessesRoute
  SpcRoute: typeof SpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spc': {
      id: '/spc'
      path: '/spc'
      fullPath: '/spc'
      preLoaderRoute: typeof SpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcessesRoute: ProcessesRoute,
  SpcRoute: SpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
